data:
    data_path: "/mnt/hdd_1A/ds_project/dataset/monuseg_patches"
    
optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.00005
    beta1: 0.9
    amsgrad: false
    eps: 0.00000001
    grad_clip: 1.0
model:
    name: "Monuseg_Unet"