data:
    data_path: "/mnt/hdd_1A/ds_project/dataset/monuseg_patches"
    
optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.00005
    beta1: 0.9
    amsgrad: false
    eps: 0.00000001
    grad_clip: 1.0

model:
    name: "Monuseg_Unet_Wavelet_NoCLIP_CrossAttn_NoGAN"

wavelet_model:
    name: "Monuseg_Unet_wavelet_NoCLIP_CrossAttn_NoGAN"
    nz: 100
    # in_channels: 6
    patch_size: 1
    num_channels: 12 ### input channel
    num_out_channels: 4
    num_channels_dae: 64
    ch: 64
    ch_mult: [1, 2, 2, 4, 4]
    num_res_blocks: 2
    attn_resolutions: [32, 16, 8]
    current_resolution: 128
    not_use_tanh: False
    z_emb_dim: 256
    t_emb_dim: 256
    resamp_with_conv: True
    conditional: True # noise-conditional
    fir: True
    fir_kernel: [1, 3, 3, 1]
    skip_rescale: True
    progressive_combine: 'sum' # choices=['sum', 'cat']
    n_mlp: 3
    centered: True
    dropout: 0.5
    use_clip: False
    ema: True
    ema_decay: 0.9999
    cross_attn: False

clip:
    image_resolution: 224
    # clip_model: "ViT-L/14" # RN50 / RN101 / RN50x4 / RN50x16 / RN50x64 / ViT-B/32 / ViT-B/16 / ViT-L/14 / ViT-L/14@336px
    # clip_chn: 768
    clip_model: "ViT-B/32" # RN50 / RN101 / RN50x4 / RN50x16 / RN50x64 / ViT-B/32 / ViT-B/16 / ViT-L/14 / ViT-L/14@336px   
    clip_chn: 512